import { BaseContract } from "./contractTypes"; // Reusing BaseContract for common fields

export interface BasePettyCash extends BaseContract {
  CreatedID?: number;
  UpdatedID?: number;
  DeletedID?: number;
}

export interface PettyCashVoucher {
  // Common Parameters from SP (header level)
  PostingID?: number; // Made optional for create, will be returned on insert
  VoucherNo?: string; // Optional for create, can be auto-generated by SP
  TransactionDate?: string | Date;
  PostingDate?: string | Date;
  CompanyID: number;
  FiscalYearID: number;
  TotalAmount?: number; // Sum of debits/credits, calculated by SP
  CurrencyID?: number;
  ExchangeRate?: number;
  Description?: string;
  Narration?: string;
  PostingStatus?: string; // Defaulted to 'Draft' by SP
  ReceiptNo?: string;

  // Audit Parameters
  CurrentUserID?: number;
  CurrentUserName?: string;

  // Joined fields (for display purposes, not direct input)
  CompanyName?: string;
  FYDescription?: string;
  CurrencyName?: string;
}

// New interfaces for JSON arrays passed to the stored procedure
export interface PettyCashEntry {
  AccountID: number;
  Amount: number;
  Description?: string;
  Narration?: string;
  CostCenter1ID?: number;
  CostCenter2ID?: number;
  CostCenter3ID?: number;
  CostCenter4ID?: number;
}

export interface PettyCashVoucherPostingLine {
  PostingID: number;
  AccountID: number;
  TransactionType: "Debit" | "Credit";
  DebitAmount: number;
  CreditAmount: number;
  CostCenter1ID?: number;
  CostCenter2ID?: number;
  CostCenter3ID?: number;
  CostCenter4ID?: number;
  AccountCode?: string;
  AccountName?: string;
  CostCenter1Name?: string;
  CostCenter2Name?: string;
  CostCenter3Name?: string;
  CostCenter4Name?: string;
  LineDescription?: string; // Added to distinguish from header Description
  LineNarration?: string; // Added to distinguish from header Narration
}

export interface PettyCashSearchParams {
  searchText?: string;
  filterFromDate?: string | Date;
  filterToDate?: string | Date;
  filterPostingStatus?: string;
  filterCompanyID?: number;
  filterFiscalYearID?: number;
  filterAccountID?: number; // Changed from filterExpenseAccountID
}

// Request parameters for petty cash voucher operations
export interface PettyCashCreateRequest {
  voucher: Omit<PettyCashVoucher, "PostingID" | "TotalAmount">; // Omit generated fields
  debitEntries: PettyCashEntry[];
  creditEntries: PettyCashEntry[];
}

export interface PettyCashUpdateRequest {
  voucher: Pick<
    PettyCashVoucher,
    "VoucherNo" | "TransactionDate" | "PostingDate" | "CompanyID" | "FiscalYearID" | "CurrencyID" | "ExchangeRate" | "Description" | "Narration" | "ReceiptNo" | "PostingStatus"
  >;
  debitEntries: PettyCashEntry[];
  creditEntries: PettyCashEntry[];
}

export interface PettyCashReverseRequest {
  VoucherNo: string; // Reversal is by VoucherNo, not PostingID
  reversalReason: string;
}

// API response structure (reusing from other types if identical)
export interface ApiResponse<T = any> {
  Status: number;
  Message: string;
  NewPostingID?: number; // Renamed to clarify it's the main ID
  VoucherNo?: string;
  ReversalVoucherNo?: string;
  [key: string]: any;
  data?: T;
  table1?: T; // For sp results
  table2?: T; // For sp results
}
